load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

RULES_JAVA_WAR_TAG = "0.1.0"

http_archive(
    name = "io_bazel_rules_java_war",
    strip_prefix = "rules_java_war-%s" % RULES_JAVA_WAR_TAG,
    url = "https://github.com/bmuschko/rules_java_war/archive/%s.tar.gz" % RULES_JAVA_WAR_TAG,
    sha256 = "d9eb30e8ea2a52c9857c9d5ffcb08d8ce3172ed153338be67bfe12310f3d0eca",
)