dist: xenial
install: true
language: java

jdk:
  - openjdk8

env:
  global:
    - BAZEL_VERSION="0.27.0"
    - EXAMPLES_DIR="$TRAVIS_BUILD_DIR/examples"

before_install:
  - sudo apt-get install pkg-config zip g++ zlib1g-dev unzip python3
  - wget -O install.sh "https://github.com/bazelbuild/bazel/releases/download/$BAZEL_VERSION/bazel-$BAZEL_VERSION-installer-linux-x86_64.sh"
  - chmod +x install.sh
  - ./install.sh --user
  - rm -f install.sh

script:
  # Execute tests and generate documentation for rules
  - bazel test //tests:test-suite
  - bazel build //java_war:java-war-docs

  # Execute example projects
  - cd $EXAMPLES_DIR/minimal; bazel build //:web-app
  - cd $EXAMPLES_DIR/custom; bazel build //:web-app