= Bazel rules for creating a Java Web Archive (WAR) image:https://travis-ci.org/bmuschko/rules_java_war.svg?branch=master["Build Status", link="https://travis-ci.org/bmuschko/rules_java_war"]

== Overview

The rules provide a way for creating a https://docs.oracle.com/javaee/6/tutorial/doc/bnadx.html[Java Web Archive (WAR)]. The project is compatible with the standard https://github.com/bazelbuild/rules_java[rules_java] and https://github.com/bazelbuild/rules_jvm_external[rules_jvm_external].

== Setup

The easiest way to use the rules is by adding the following to your `WORKSPACE` file:

[source,python]
----
load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

RULES_JAVA_WAR_TAG = "0.1.0"

http_archive(
    name = "io_bazel_rules_java_war",
    strip_prefix = "rules_java_war-%s" % RULES_JAVA_WAR_TAG,
    url = "https://github.com/bmuschko/rules_java_war/archive/%s.tar.gz" % RULES_JAVA_WAR_TAG,
    sha256 = "38011f979713c4aefd43ab56675ce4c6c14bc949b128c3a303f1f57ebe4bfeac",
)
----

== Basic Example

Suppose you are following the typical directory structure for a Java web application:

----
.
├── BUILD
├── WORKSPACE
└── src
    └── main
        ├── java
        │   └── com
        │       └── bmuschko
        │           └── web
        │               └── SimpleServlet.java
        └── webapp
            ├── WEB-INF
            │   └── web.xml
            ├── css
            │   └── style.css
            ├── index.html
            └── js
                └── dynamic.js
----

To build the WAR file for the application, a `BUILD` on the root level could look as follows:

[source,python]
----
load("@io_bazel_rules_java_war//java_war:defs.bzl", "java_war")

java_war(
    name = "minimal",
    java_srcs = glob(["src/main/java/**/*.java"]),
    deps = [
        "@maven//:org_mortbay_jetty_servlet_api",
        "@maven//:ch_qos_logback_logback_classic",
    ],
)
----

Under the hood, the macro named `java_war` will generate the `java_library` of the application and then include it as dependency for the WAR file.

The result WAR file contains the content shown below. The rule will include the transitive closure of runtime dependencies. The dependency `org_mortbay_jetty_servlet_api` was declared as "compile-only" dependency and therefore isn't included.

----
$ java -tf minimal.war
WEB-INF/web.xml
css/style.css
index.html
js/dynamic.js
WEB-INF/lib/liblibextdeps.jar
WEB-INF/lib/logback-classic-1.1.2.jar
WEB-INF/lib/slf4j-api-1.7.6.jar
WEB-INF/lib/logback-core-1.1.2.jar
----

== API

=== war

++++
<pre>
war(<a href="#war-name">name</a>, <a href="#war-compression">compression</a>, <a href="#war-deps">deps</a>, <a href="#war-web_app_root">web_app_root</a>, <a href="#war-web_app_srcs">web_app_srcs</a>)
</pre>
++++

Rule for generating a Java Web Archive (WAR).


==== Attributes

++++
<table class="params-table">
  <colgroup>
    <col class="col-param" />
    <col class="col-description" />
  </colgroup>
  <tbody>
    <tr id="war-name">
      <td><code>name</code></td>
      <td>
        <a href="https://bazel.build/docs/build-ref.html#name">Name</a>; required
        <p>
          A unique name for this target.
        </p>
      </td>
    </tr>
    <tr id="war-compression">
      <td><code>compression</code></td>
      <td>
        Boolean; required
        <p>
          Enables compression for the WAR file.
        </p>
      </td>
    </tr>
    <tr id="war-deps">
      <td><code>deps</code></td>
      <td>
        <a href="https://bazel.build/docs/build-ref.html#labels">List of labels</a>; optional
        <p>
          Dependencies for this target.
        </p>
      </td>
    </tr>
    <tr id="war-web_app_root">
      <td><code>web_app_root</code></td>
      <td>
        String; required
        <p>
          Root directory containing web application files (e.g. web.xml, CSS or JavaScript files).
        </p>
      </td>
    </tr>
    <tr id="war-web_app_srcs">
      <td><code>web_app_srcs</code></td>
      <td>
        <a href="https://bazel.build/docs/build-ref.html#labels">List of labels</a>; required
        <p>
          Source files to be included fromt the web application root directory.
        </p>
      </td>
    </tr>
  </tbody>
</table>
++++

=== java_war

++++
<pre>
java_war(<a href="#java_war-name">name</a>, <a href="#java_war-web_app_dir">web_app_dir</a>, <a href="#java_war-java_srcs">java_srcs</a>, <a href="#java_war-deps">deps</a>, <a href="#java_war-compression">compression</a>, <a href="#java_war-kwargs">kwargs</a>)
</pre>
++++

Creates a Java Web Archive (WAR).

Automatically creates a Java library and bundles it with the web application files and any dependencies.
For more information on the internal structure of a WAR file, see the https://docs.oracle.com/javaee/6/tutorial/doc/bnadx.html[official documentation].


==== Parameters

++++
<table class="params-table">
  <colgroup>
    <col class="col-param" />
    <col class="col-description" />
  </colgroup>
  <tbody>
    <tr id="java_war-name">
      <td><code>name</code></td>
      <td>
        required.
        <p>
          A unique name for this rule.
        </p>
      </td>
    </tr>
    <tr id="java_war-web_app_dir">
      <td><code>web_app_dir</code></td>
      <td>
        optional. default is <code>"src/main/webapp"</code>
        <p>
          The root web application directory.
        </p>
      </td>
    </tr>
    <tr id="java_war-java_srcs">
      <td><code>java_srcs</code></td>
      <td>
        optional. default is <code>[]</code>
        <p>
          Java source files for compilation.
        </p>
      </td>
    </tr>
    <tr id="java_war-deps">
      <td><code>deps</code></td>
      <td>
        optional. default is <code>[]</code>
        <p>
          Dependencies for this java_library target.
        </p>
      </td>
    </tr>
    <tr id="java_war-compression">
      <td><code>compression</code></td>
      <td>
        optional. default is <code>False</code>
        <p>
          Enables compression for the WAR.
        </p>
      </td>
    </tr>
    <tr id="java_war-kwargs">
      <td><code>kwargs</code></td>
      <td>
        optional.
      </td>
    </tr>
  </tbody>
</table>
++++